### ISSUE TITLE
点击生成音频报如下的错误

### ISSUE THREAD

**Issue by anstonjie** [v3ucn/CosyVoice_For_Windows#1]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\gradio\queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\gradio\blocks.py", line 1945, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\gradio\blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\gradio\utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "E:\ai3\CosyVoice_For_Windows\webui.py", line 121, in generate_audio
    output = cosyvoice.inference_sft(tts_text, sft_dropdown)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai3\CosyVoice_For_Windows\cosyvoice\cli\cosyvoice.py", line 57, in inference_sft
    return {'tts_speech': torch.concat(tts_speeches, dim=1)}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: torch.cat(): expected a non-empty list of Tensors

**Comment by v3ucn** [comment]
这个bug已经修复，是因为文本后面没有标点，导致split后为空

**Comment by v3ucn** [comment]
拉取最新代码即可

**Comment by anstonjie** [comment]
好的谢谢

**Comment by gm800324** [comment]
RuntimeError: torch.cat(): expected a non-empty list of Tensors

**Comment by gm800324** [comment]
It's still a mistake
