### ISSUE TITLE
出现组件不存在的问题，不知道哪没装好， There is no such entity as cosyvoice.utils.common.ras_sampling

### ISSUE THREAD

**Issue by clhui** [v3ucn/CosyVoice_For_Windows#27]
D:\Users\chen\PycharmProjects\CosyVoice_For_Windows\cosyvoice\cli\cosyvoice.py:17: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend('soundfile')
2024-09-01 21:13:07,159 - modelscope - INFO - PyTorch version 2.4.0+cu118 Found.
2024-09-01 21:13:07,161 - modelscope - INFO - Loading ast index from C:\Users\chen\.cache\modelscope\ast_indexer
2024-09-01 21:13:07,341 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 36529b52030c956cf544095a4b0aa3e5 and a total number of 980 components indexed
D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\torch\_jit_internal.py:745: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
Traceback (most recent call last):
  File "D:\Users\chen\PycharmProjects\CosyVoice_For_Windows\test.py", line 15, in <module>
    cosyvoice = CosyVoice('./pretrained_models/CosyVoice-300M-SFT')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\chen\PycharmProjects\CosyVoice_For_Windows\cosyvoice\cli\cosyvoice.py", line 56, in __init__
    configs = load_hyperpyyaml(f)
              ^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\hyperpyyaml\core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 116, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 120, in construct_document
    data = self.construct_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\hyperpyyaml\core.py", line 480, in _construct_object
    args, kwargs = _load_node(loader, node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\hyperpyyaml\core.py", line 434, in _load_node
    kwargs = loader.construct_mapping(node, deep=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 429, in construct_mapping
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\hyperpyyaml\core.py", line 491, in _construct_name
    raise ImportError("There is no such entity as %s" % callable_string)
ImportError: There is no such entity as cosyvoice.utils.common.ras_sampling

**Comment by Qggg** [comment]
I encounter the same problem as you, and as the answer of orignal version of this project ,the author revise some script of model, we can find the old version model file, or wait the author of this project to update the code. https://github.com/FunAudioLLM/CosyVoice/issues/325

**Comment by Qggg** [comment]
By the way, I can't find the old version model in https://www.modelscope.cn/models/iic/CosyVoice-300M/files

**Comment by Qggg** [comment]
> D:\Users\chen\PycharmProjects\CosyVoice_For_Windows\cosyvoice\cli\cosyvoice.py:17: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call. torchaudio.set_audio_backend('soundfile') 2024-09-01 21:13:07,159 - modelscope - INFO - PyTorch version 2.4.0+cu118 Found. 2024-09-01 21:13:07,161 - modelscope - INFO - Loading ast index from C:\Users\chen.cache\modelscope\ast_indexer 2024-09-01 21:13:07,341 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 36529b52030c956cf544095a4b0aa3e5 and a total number of 980 components indexed D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\torch_jit_internal.py:745: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {} warnings.warn( Traceback (most recent call last): File "D:\Users\chen\PycharmProjects\CosyVoice_For_Windows\test.py", line 15, in cosyvoice = CosyVoice('./pretrained_models/CosyVoice-300M-SFT') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Users\chen\PycharmProjects\CosyVoice_For_Windows\cosyvoice\cli\cosyvoice.py", line 56, in **init** configs = load_hyperpyyaml(f) ^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\hyperpyyaml\core.py", line 188, in load_hyperpyyaml hparams = yaml.load(yaml_stream, Loader=loader) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\yaml__init__.py", line 81, in load return loader.get_single_data() ^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 116, in get_single_data return self.construct_document(node) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 120, in construct_document data = self.construct_object(node) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object data = self.construct_non_recursive_object(node) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 188, in construct_non_recursive_object for _dummy in generator: File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 633, in construct_yaml_map value = self.construct_mapping(node) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 429, in construct_mapping return BaseConstructor.construct_mapping(self, node, deep=deep) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 244, in construct_mapping value = self.construct_object(value_node, deep=deep) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object data = self.construct_non_recursive_object(node) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 183, in construct_non_recursive_object data = constructor(self, tag_suffix, node) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\hyperpyyaml\core.py", line 480, in _construct_object args, kwargs = _load_node(loader, node) ^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\hyperpyyaml\core.py", line 434, in _load_node kwargs = loader.construct_mapping(node, deep=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 429, in construct_mapping ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 244, in construct_mapping value = self.construct_object(value_node, deep=deep) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object data = self.construct_non_recursive_object(node) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\ruamel\yaml\constructor.py", line 183, in construct_non_recursive_object data = constructor(self, tag_suffix, node) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\software\miniconda3\envs\cosyvoicewin\Lib\site-packages\hyperpyyaml\core.py", line 491, in _construct_name raise ImportError("There is no such entity as %s" % callable_string) ImportError: There is no such entity as cosyvoice.utils.common.ras_sampling

You can comment out the following lines of cosyvoice.yaml,then rerun the script. 

    sampling: !name:cosyvoice.utils.common.ras_sampling
        top_p: 0.8
        top_k: 25
        win_size: 10
        tau_r: 0.1

**Comment by clhui** [comment]
按方法已解决
