### ISSUE TITLE
 There is no such entity as cosyvoice.utils.common.ras_sampling这是什么原因

### ISSUE THREAD

**Issue by saviourp** [v3ucn/CosyVoice_For_Windows#31]
Traceback (most recent call last):
  File "D:\software\JetBrains\project\AIshuziren\CosyVoice_For_Windows\webui_jie.py", line 213, in <module>
    cosyvoice = CosyVoice(args.model_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\project\AIshuziren\CosyVoice_For_Windows\cosyvoice\cli\cosyvoice.py", line 56, in __init__
    configs = load_hyperpyyaml(f)
              ^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\hyperpyyaml\core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\ruamel\yaml\constructor.py", line 116, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\ruamel\yaml\constructor.py", line 120, in construct_document
    data = self.construct_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\ruamel\yaml\constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\ruamel\yaml\constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\ruamel\yaml\constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\ruamel\yaml\constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\ruamel\yaml\constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\hyperpyyaml\core.py", line 480, in _construct_object
    args, kwargs = _load_node(loader, node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\hyperpyyaml\core.py", line 434, in _load_node
    kwargs = loader.construct_mapping(node, deep=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\ruamel\yaml\constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\ruamel\yaml\constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\ruamel\yaml\constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\JetBrains\Anaconda3\envs\cosyvoice\Lib\site-packages\hyperpyyaml\core.py", line 491, in _construct_name
    raise ImportError("There is no such entity as %s" % callable_string)
ImportError: There is no such entity as cosyvoice.utils.common.ras_sampling
(

**Comment by botnang** [comment]
阿里那边模型升级了，这边代码还没更新。
建议下载这边的整合包，提取里面的旧模型使用。

**Comment by sinwo0O** [comment]
选确定你用的哪个模型。以CosyVoice-300M为例，编辑文件CosyVoice_For_Windows\pretrained_models\CosyVoice-300M\cosyvoice.yaml。搜索ras_sampling，把相关内容都注释掉。
`    # sampling: !name:cosyvoice.utils.common.ras_sampling
    #     top_p: 0.8
    #     top_k: 25
    #     win_size: 10
    #     tau_r: 0.1`
