### ISSUE TITLE
在新机器上安装全套环境，遇到ModuleNotFoundError: No module named 'whisper'

### ISSUE THREAD

**Issue by sinwo0O** [v3ucn/CosyVoice_For_Windows#9]
(cosyvoice) PS C:\CosyVoice_For_Windows> python .\test.py
C:\CosyVoice_For_Windows\cosyvoice\cli\cosyvoice.py:17: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend('soundfile')
2024-07-17 14:37:10,483 - modelscope - INFO - PyTorch version 2.3.1+cu121 Found.
2024-07-17 14:37:10,501 - modelscope - INFO - Loading ast index from ./.cache/modelscope\ast_indexer
2024-07-17 14:37:10,781 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 d2ef888772ce8aec4bd967a5a6c349e3 and a total number of 980 components indexed
transformer is not installed, please install it if you want to use related modules
Traceback (most recent call last):
  File "C:\CosyVoice_For_Windows\test.py", line 11, in <module>
    from cosyvoice.cli.cosyvoice import CosyVoice
  File "C:\CosyVoice_For_Windows\cosyvoice\cli\cosyvoice.py", line 20, in <module>
    from cosyvoice.cli.frontend import CosyVoiceFrontEnd
  File "C:\CosyVoice_For_Windows\cosyvoice\cli\frontend.py", line 18, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'
这个是什么原因？

**Comment by sinwo0O** [comment]
似乎是这台机器连不上官网镜像源，就换成了国内清华的镜像源，结果就没有安装whisper这个包

**Comment by v3ucn** [comment]
可用 pip 安装一下

**Comment by sinwo0O** [comment]
> 可用 pip 安装一下
能帮我看一下正确的whisper版本号吗？我直接pip install whisper，运行时又报另外一个错误。
Traceback (most recent call last):
  File "C:\CosyVoice_For_Windows\test.py", line 11, in <module>
    from cosyvoice.cli.cosyvoice import CosyVoice
  File "C:\CosyVoice_For_Windows\cosyvoice\cli\cosyvoice.py", line 20, in <module>
    from cosyvoice.cli.frontend import CosyVoiceFrontEnd
  File "C:\CosyVoice_For_Windows\cosyvoice\cli\frontend.py", line 18, in <module>
    import whisper
  File "C:\Users\vipuser\miniconda3\envs\cosyvoice\Lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vipuser\miniconda3\envs\cosyvoice\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by v3ucn** [comment]
> > 可用 pip 安装一下
> 
> 能帮我看一下正确的whisper版本号吗？我直接pip install whisper，运行时又报另外一个错误。 Traceback (most recent call last): File "C:\CosyVoice_For_Windows\test.py", line 11, in from cosyvoice.cli.cosyvoice import CosyVoice File "C:\CosyVoice_For_Windows\cosyvoice\cli\cosyvoice.py", line 20, in from cosyvoice.cli.frontend import CosyVoiceFrontEnd File "C:\CosyVoice_For_Windows\cosyvoice\cli\frontend.py", line 18, in import whisper File "C:\Users\vipuser\miniconda3\envs\cosyvoice\Lib\site-packages\whisper.py", line 69, in libc = ctypes.CDLL(libc_name) ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\vipuser\miniconda3\envs\cosyvoice\Lib\ctypes__init__.py", line 366, in **init** if '/' in name or '\' in name: ^^^^^^^^^^^ TypeError: argument of type 'NoneType' is not iterable

命令错了，应该是: pip install openai-whisper

**Comment by sdrz001** [comment]
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:739 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
